export interface Location {
  latitude: number;
  longitude: number;
  address: string;
  placeId: string;
  placeName?: string;
}

export interface OpeningHours {
  from?: string; // Time in HH:MM format
  to?: string; // Time in HH:MM format
}

export interface DayOpeningHours {
  monday?: OpeningHours;
  tuesday?: OpeningHours;
  wednesday?: OpeningHours;
  thursday?: OpeningHours;
  friday?: OpeningHours;
  saturday?: OpeningHours;
  sunday?: OpeningHours;
}

export interface RefreshTokenSession {
  sessionId: string; // Unique server-managed stable ID for session switching
  jti: string; // JWT ID for token rotation tracking
  tokenHash: string; // bcrypt hash of refresh token (never expose raw token)
  userAgent?: string;
  ip?: string;
  deviceName?: string;
  createdAt: Date;
  expiresAt: Date;
  lastUsedAt?: Date; // Track last activity within this session
}

// Session tracking - consolidated online status and devices
export interface Device {
  name: string;
  ipAddress?: string;
}

export interface SessionTrack {
  isOnline: boolean;
  lastSeen?: Date;
  devices: Device[]; // List of active devices with name and IP
}

// FCM device token for push notifications
export interface FcmToken {
  token: string;
  deviceId: string; // Unique device identifier from the client
  platform: 'ios' | 'android' | 'web';
  createdAt?: Date;
}

export interface OAuth {
  google?: {
    id?: string;
    email?: string;
    name?: string;
    picture?: string;
    verified?: boolean;
  };
}

export interface User {
  _id?: any; // MongoDB ObjectId - optional since it's only present after DB operations
  email: string;
  type: 'user' | 'client' | 'lounge' | 'admin' | 'agent';
  password?: string; // Optional for OAuth users
  phoneNumber?: string; // Optional
  gender?: 'male' | 'female' | 'unisex' | 'kids'; // Optional
  firstName?: string; // Client-specific
  lastName?: string; // Client-specific
  bio?: string;
  theme?: string;
  language?: string; // User language preference (e.g. 'en', 'ar', 'fr')
  loungeTitle?: string; // Lounge-specific
  openingHours?: DayOpeningHours; // Lounge-specific
  averageRating?: number; // Lounge-specific — denormalized from ratings
  ratingCount?: number; // Lounge-specific — denormalized from ratings
  likeCount?: number; // Lounge-specific — denormalized from likes
  followersCount?: number; // Denormalized from follows
  followingCount?: number; // Denormalized from follows
  location?: Location;
  profileImage?: { url?: string; publicId?: string };
  coverImage?: { url?: string; publicId?: string };
  isBlocked?: boolean;
  emailVerification?: Array<{ isVerified: boolean; verifCode?: string; verifCodeExpiresAt?: Date }>;
  refreshTokens?: RefreshTokenSession[]; // Multi-device session support
  sessionTrack: SessionTrack; // Consolidated session tracking
  fcmTokens?: FcmToken[]; // Push notification device tokens
  oauth?: OAuth; // OAuth provider data
  failedLoginAttempts?: number; // Account lockout counter
  lockUntil?: Date; // Account lockout expiry
  passwordChangedAt?: Date; // Last password change timestamp

  // ─── Agent-specific fields (only meaningful when type === 'agent') ───
  /** Display name shown in the queue UI (e.g. "Agent Sarah"). Optional, agent-only. */
  agentName?: string;
  /** Reference to the parent Lounge user this agent works for. Required when type === 'agent'. */
  parentLounge?: any;
  /** Lounge services this agent is qualified to perform. Agent-only. */
  services?: any[];
  /** Whether this agent is currently accepting walk-in/queue bookings. Agent-only. */
  acceptQueueBooking?: boolean;

  createdAt?: Date; // Auto-generated by Mongoose timestamps
  updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

// Client extends User
export interface Client extends User {
  // Client-specific fields
  firstName?: string;
  lastName?: string;
}

// Lounge extends User
export interface Lounge extends User {
  // Lounge-specific fields
  LoungeTitle?: string;
  openingHours?: DayOpeningHours; // Opening hours for each day of the week
}

// Admin extends User
export interface Admin extends User {
  // Admin-specific fields
  adminLevel?: 'super' | 'regular';
}

// Agent extends User — a stand-alone authenticated user that works for a Lounge
// and manages their own daily queue. Agents are created by Lounges or Admins
// (never via public signup) and log in via the standard /v1/auth/login flow.
export interface Agent extends User {
  type: 'agent';
  /** Reference to the parent Lounge user this agent works for. */
  parentLounge: any;
  /** Lounge services this agent is qualified to perform. */
  services: any[];
  /** Display name shown in the queue UI. */
  agentName?: string;
  /** Whether this agent is currently accepting walk-in/queue bookings. */
  acceptQueueBooking?: boolean;
}

// Response type for online users query
export interface OnlineUserInfo {
  _id: string;
  email: string;

  sessionTrack: SessionTrack;
  activeSessions: number;
  hasMultipleSessions: boolean;
}
