export interface Location {
  latitude: number;
  longitude: number;
  address: string;
  placeId: string;
}

export interface RefreshTokenSession {
  jti: string;
  tokenHash: string;
  userAgent?: string;
  ip?: string;
  deviceName?: string;
  createdAt: Date;
  expiresAt: Date;
}

// Session tracking - consolidated online status and devices
export interface Device {
  name: string;
  ipAddress?: string;
}

export interface SessionTrack {
  isOnline: boolean;
  lastSeen?: Date;
  devices: Device[]; // List of active devices with name and IP
}

export interface OAuth {
  google?: {
    id?: string;
    email?: string;
    name?: string;
    picture?: string;
    verified?: boolean;
  };
}

export interface User {
  _id: string;
  email: string;
  type: 'user' | 'client' | 'lounge' | 'admin';
  password?: string; // Optional for OAuth users
  phoneNumber?: string; // Optional
  gender?: 'male' | 'female' | 'both'; // Optional
  firstName?: string; // Client-specific
  lastName?: string; // Client-specific
  bio?: string;
  loungeTitle?: string; // Lounge-specific
  services?: string[]; // Lounge-specific
  location?: Location;
  profileImage?: { url?: string; publicId?: string };
  isBlocked?: boolean;
  emailVerification?: Array<{ isVerified: boolean; verifCode?: string; verifCodeExpiresAt?: Date }>;
  refreshTokens?: RefreshTokenSession[]; // Multi-device session support
  sessionTrack: SessionTrack; // Consolidated session tracking
  oauth?: OAuth; // OAuth provider data
  createdAt?: Date; // Auto-generated by Mongoose timestamps
  updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

// Client extends User
export interface Client extends User {
  // Client-specific fields
  firstName?: string;
  lastName?: string;
}

// Lounge extends User
export interface Lounge extends User {
  // Lounge-specific fields
  LoungeTitle?: string;
  services?: string[]; // Array of services offered
}

// Admin extends User
export interface Admin extends User {
  // Admin-specific fields
  adminLevel?: 'super' | 'regular';
}

// Response type for online users query
export interface OnlineUserInfo {
  _id: string;
  email: string;

  sessionTrack: SessionTrack;
  activeSessions: number;
  hasMultipleSessions: boolean;
}
