export interface Location {
  latitude: number;
  longitude: number;
  address: string;
  placeId: string;
}

export interface OpeningHours {
  from?: string; // Time in HH:MM format
  to?: string; // Time in HH:MM format
}

export interface DayOpeningHours {
  monday?: OpeningHours;
  tuesday?: OpeningHours;
  wednesday?: OpeningHours;
  thursday?: OpeningHours;
  friday?: OpeningHours;
  saturday?: OpeningHours;
  sunday?: OpeningHours;
}

export enum ServiceStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
}

export enum ServiceSuggestionStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  IMPLEMENTED = 'implemented',
}

export interface ServiceCategory {
  _id: string;
  name: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface Service {
  _id: string;
  name: string;
  slug: string;
  categoryId: string;
  baseDuration?: number;
  status: ServiceStatus;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ServiceSuggestion {
  _id: string;
  name: string;
  description?: string;
  status: ServiceSuggestionStatus;
  loungeId: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface LoungeService {
  _id: string;
  loungeId: string;
  serviceId: string;
  price: number;
  duration: number;
  description?: string;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface RefreshTokenSession {
  jti: string;
  tokenHash: string;
  userAgent?: string;
  ip?: string;
  deviceName?: string;
  createdAt: Date;
  expiresAt: Date;
}

// Session tracking - consolidated online status and devices
export interface Device {
  name: string;
  ipAddress?: string;
}

export interface SessionTrack {
  isOnline: boolean;
  lastSeen?: Date;
  devices: Device[]; // List of active devices with name and IP
}

export interface OAuth {
  google?: {
    id?: string;
    email?: string;
    name?: string;
    picture?: string;
    verified?: boolean;
  };
}

export interface User {
  _id: string;
  email: string;
  type: 'user' | 'client' | 'lounge' | 'admin';
  password?: string; // Optional for OAuth users
  phoneNumber?: string; // Optional
  gender?: 'male' | 'female' | 'unisex' | 'kids'; // Optional
  firstName?: string; // Client-specific
  lastName?: string; // Client-specific
  bio?: string;
  loungeTitle?: string; // Lounge-specific
  openingHours?: DayOpeningHours; // Lounge-specific
  location?: Location;
  profileImage?: { url?: string; publicId?: string };
  isBlocked?: boolean;
  emailVerification?: Array<{ isVerified: boolean; verifCode?: string; verifCodeExpiresAt?: Date }>;
  refreshTokens?: RefreshTokenSession[]; // Multi-device session support
  sessionTrack: SessionTrack; // Consolidated session tracking
  oauth?: OAuth; // OAuth provider data
  createdAt?: Date; // Auto-generated by Mongoose timestamps
  updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

// Client extends User
export interface Client extends User {
  // Client-specific fields
  firstName?: string;
  lastName?: string;
}

// Lounge extends User
export interface Lounge extends User {
  // Lounge-specific fields
  LoungeTitle?: string;
  openingHours?: DayOpeningHours; // Opening hours for each day of the week
}

// Admin extends User
export interface Admin extends User {
  // Admin-specific fields
  adminLevel?: 'super' | 'regular';
}

// Response type for online users query
export interface OnlineUserInfo {
  _id: string;
  email: string;

  sessionTrack: SessionTrack;
  activeSessions: number;
  hasMultipleSessions: boolean;
}
