export interface Location {
  latitude: number;
  longitude: number;
  address: string;
  placeId: string;
}

export interface RefreshTokenSession {
  jti: string;
  tokenHash: string;
  userAgent?: string;
  ip?: string;
  deviceName?: string;
  createdAt: Date;
  expiresAt: Date;
}

// Session tracking - consolidated online status and devices
export interface Device {
  name: string;
  ipAddress?: string;
}

export interface SessionTrack {
  isOnline: boolean;
  lastSeen?: Date;
  devices: Device[]; // List of active devices with name and IP
}

export interface User {
  _id: string;
  email: string;
  password: string;
  role: 'admin' | 'user' | 'barber';
  username: string;
  phoneNumber: string;
  gender: 'male' | 'female' | 'other';
  location?: Location;
  profileImage?: string;
  isBlocked?: boolean;
  refreshTokens?: RefreshTokenSession[]; // Multi-device session support
  sessionTrack: SessionTrack; // Consolidated session tracking
  createdAt?: Date; // Auto-generated by Mongoose timestamps
  updatedAt?: Date; // Auto-generated by Mongoose timestamps
}

// Response type for online users query
export interface OnlineUserInfo {
  _id: string;
  email: string;
  username: string;
  role: 'admin' | 'user' | 'barber';
  sessionTrack: SessionTrack;
  activeSessions: number;
  hasMultipleSessions: boolean;
}
